import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import NextTopLoader from "nextjs-toploader";
import { useEffect } from "react";
import { MouseTracker } from "@/components/MouseTracker";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Harish Soni || MERN Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="#ffffff" height={3} />
        <MouseTracker />
        {children}
      </body>
    </html>
  );
}
